### ISSUE TITLE
Create develop branch

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#146]
`develop` branch allows:

1. Staging changes prior to releasing
1. Avoid merging PRs to `master` and causing release per PR
1. Handle situations like with choco maintainers when they want to see changes with a locked version.
1. Paves our way to use something like GitVersion

**TODO**
- [x] Ensure releases are only made from `master` branch @seanfeldman
- [x] Make `develop` the default branch
- [x] Make `develop` protected

**Comment by SeanFeldman** [comment]
@paolosalvatori I've created `develop` branch. We should make it the default so that all PRs go against it by default.

@tomkerkhove once `develop` is in place, we can have the same version package built with all the changes w/o causing releases flood.

**Comment by tomkerkhove** [comment]
Sounds good to me, thanks! Ping me if you need help.

**Comment by paolosalvatori** [comment]
Sounds good to me, thanks Sean.

**Comment by SeanFeldman** [comment]
@paolosalvatori could you please complete the settings access? 
`master` is still the default branch 😞 
Thanks.

**Comment by paolosalvatori** [comment]
Ping me offline and let's do it together

**Comment by SeanFeldman** [comment]
Done.
